;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]
bg = #1A1B26
fg = #F1F1F1
mb = #222330

red = #F7768E
pink = #FF0677
purple = #583794
blue = #7AA2F7
blue-arch = #0A9CF5
cyan = #7DCFFF
teal = #00B19F
green = #9ECE6A
lime = #B9C244
yellow = #E0AF68
amber = #FBC02D
orange = #E57C46
brown = #AC8476
grey = #8C8C8C
indigo = #6C77BB
blue-gray = #6D8895

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
