;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/bi]
type = custom/text
label = "%{T5}%{T-}"
label-foreground = ${color.mb}
label-background = ${color.bg}

[module/bd]
type = custom/text
label = "%{T5}%{T-}"
label-foreground = ${color.mb}
label-background = ${color.bg}

[module/sep]
type = custom/text
label = " "
label-foreground = ${color.bg}

[module/dots]
type = custom/text
label = " 󰇙 "
label-font = 3
label-foreground = ${color.blue-gray}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
