# =============================================================================
# Powerlevel10k Configuration File
# =============================================================================
# Generated by Powerlevel10k configuration wizard on 2023-12-14 at 19:44 CET.
# Modified to use dynamic directory icons from lsd (LSDeluxe) configuration.
#
# Based on: romkatv/powerlevel10k/config/p10k-lean-8colors.zsh, checksum 27973.
# Wizard options: nerdfont-complete + powerline, small icons, unicode,
# lean_8colors, 1 line, sparse, many icons, concise, instant_prompt=verbose.
#
# To regenerate this config, run: p10k configure
# =============================================================================

# -----------------------------------------------------------------------------
# Temporarily change shell options for configuration
# -----------------------------------------------------------------------------
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # Clear all existing Powerlevel9k/10k configuration
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  # Require Zsh version 5.1 or higher
  [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

  # ===========================================================================
  # PROMPT SEGMENTS CONFIGURATION
  # ===========================================================================
  # Define which segments appear on the left side of the prompt
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    os_icon                 # Operating system identifier
    user                    # Current username
    dir                     # Current working directory
    vcs                     # Git repository status
    command_execution_time  # Duration of last command (if > threshold)
    prompt_char             # Prompt symbol (changes on vi mode and errors)
  )

  # Define which segments appear on the right side of the prompt
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    virtualenv              # Python venv indicator when active
  )

  # virtualenv segment: show "(venv-name)" when a Python venv is active
  typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=false
  typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_WITH_PYENV=false
  typeset -g POWERLEVEL9K_VIRTUALENV_LEFT_DELIMITER='('
  typeset -g POWERLEVEL9K_VIRTUALENV_RIGHT_DELIMITER=')'
  typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=2

  # ===========================================================================
  # GENERAL APPEARANCE SETTINGS
  # ===========================================================================
  # Icon font mode - using Nerd Fonts with complete icon set
  typeset -g POWERLEVEL9K_MODE=nerdfont-complete
  typeset -g POWERLEVEL9K_ICON_PADDING=none

  # Transparent background for all segments
  typeset -g POWERLEVEL9K_BACKGROUND=

  # Remove whitespace padding around segments
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=

  # Use single space as separator between segments
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '

  # No special symbols at segment boundaries
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=

  # Show icons before segment content
  typeset -g POWERLEVEL9K_ICON_BEFORE_CONTENT=true

  # Add blank line before each prompt for readability
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

  # ===========================================================================
  # MULTILINE PROMPT SETTINGS
  # ===========================================================================
  # No decorative characters for multiline prompts
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX=
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX=
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_SUFFIX=
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX=

  # No decorative symbols at prompt boundaries
  typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL=

  # Ruler settings (horizontal line between prompts - disabled)
  typeset -g POWERLEVEL9K_SHOW_RULER=false
  typeset -g POWERLEVEL9K_RULER_CHAR='─'
  typeset -g POWERLEVEL9K_RULER_FOREGROUND=7

  # Gap character between left and right prompt segments
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR=' '
  if [[ $POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR != ' ' ]]; then
    typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=7
    typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=' '
    typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL=' '
    typeset -g POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_FIRST_SEGMENT_END_SYMBOL='%{%}'
    typeset -g POWERLEVEL9K_EMPTY_LINE_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='%{%}'
  fi

  # ===========================================================================
  # OS ICON SEGMENT
  # ===========================================================================
  # Display operating system icon (Arch Linux logo in this case)
  # Distribution badge. Kali gets its own glyph and blue; anything else keeps Arch's.
  if [[ -r /etc/os-release ]] && grep -q '^ID=kali' /etc/os-release; then
    typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND='#367BF0'
    typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION=$'\uf327 '
  else
    typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND='#0A9CF5'
    typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION='󰣇 '
  fi

  # ===========================================================================
  # PROMPT CHARACTER SEGMENT
  # ===========================================================================
  # The prompt character changes based on vi mode and last command status

  # Green color when last command succeeded
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=2

  # Red color when last command failed
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=1

  # Different symbols for different vi modes
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'   # Insert mode
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮'   # Command mode
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='V'   # Visual mode
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIOWR_CONTENT_EXPANSION='▶'   # Overwrite mode

  typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=

  # ===========================================================================
  # DIRECTORY SEGMENT
  # ===========================================================================
  # Directory path color (Tokyo Night theme amber)
  typeset -g POWERLEVEL9K_DIR_FOREGROUND='#E0AF68'

  # Truncation strategy - show unique path components
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
  typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=

  # Colors for shortened and anchor directories
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='#E0AF68'
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='#E0AF68'
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=false

  # Anchor files - directories containing these files are always shown in full
  # These typically indicate project roots
  local anchor_files=(
    .bzr .citc .git .hg .node-version .python-version .go-version .ruby-version
    .lua-version .java-version .perl-version .php-version .tool-versions
    .shorten_folder_marker .svn .terraform CVS Cargo.toml composer.json go.mod
    package.json stack.yaml
  )
  typeset -g POWERLEVEL9K_SHORTEN_FOLDER_MARKER="(${(j:|:)anchor_files})"

  # Path truncation settings
  typeset -g POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=false
  typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
  typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=80
  typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=40
  typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=50

  # Disable hyperlinks in directory path
  typeset -g POWERLEVEL9K_DIR_HYPERLINK=false

  # Show lock icon for non-writable directories
  typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=v3

  # ===========================================================================
  # DYNAMIC DIRECTORY ICONS FROM LSD
  # ===========================================================================
  # This section loads directory icons dynamically from lsd (LSDeluxe)
  # configuration files. It reads from:
  #   1. ~/.config/lsd/icons.yaml (custom icons)
  #   2. Falls back to calling lsd directly
  #   3. Uses built-in defaults as last resort
  #
  # Benefits:
  #   - Single source of truth for directory icons
  #   - Icons stay synchronized between lsd and prompt
  #   - Automatic updates when lsd config changes
  # ===========================================================================

  # Associative array to cache icons (improves performance)
  typeset -gA _LSD_DIR_ICON_CACHE

  # Path to lsd icons configuration file
  typeset -g _LSD_ICONS_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/lsd/icons.yaml"

  # Function to parse lsd icons.yaml and extract directory icons
  function _parse_lsd_icons_yaml() {
    local yaml_file="$1"
    local dir_name="$2"

    [[ ! -f "$yaml_file" ]] && return 1

    # Search in the 'name:' section of the YAML file
    # Format expected: "  dirname: icon"
    local icon=$(awk -v dir="$dir_name" '
      /^name:/ { in_name=1; next }
      /^[a-z]+:/ { in_name=0 }
      in_name && $1 == dir":" { gsub(/^[^:]+:[[:space:]]*/, ""); print; exit }
    ' "$yaml_file" 2>/dev/null)

    [[ -n "$icon" ]] && echo "$icon" && return 0
    return 1
  }

  # Function to get icon from lsd command output
  function _get_lsd_icon() {
    local dir_path="$1"

    # Check if lsd is available
    command -v lsd &>/dev/null || return 1

    # Run lsd and extract the icon (first few characters before the name)
    # Using: -d (directory only), --icon always, minimal output
    local output=$(lsd -d --icon always --icon-theme fancy "$dir_path" 2>/dev/null)

    # Extract icon (typically first 1-4 characters, before whitespace and name)
    local icon="${output%% *}"

    # Validate we got something that looks like an icon
    [[ -n "$icon" && "$icon" != "${dir_path:t}" ]] && echo "$icon" && return 0
    return 1
  }

  # Main function to determine directory icon dynamically
  function _p9k_dynamic_dir_icon() {
    local dir_name="${PWD:t}"    # Current directory name (tail of path)
    local dir_path="$PWD"        # Full path to current directory
    local icon=""
    local icon_color='#7AA2F7'   # Tokyo Night theme blue

    # -------------------------------------------------------------------------
    # Special case: Home directory always shows house icon
    # -------------------------------------------------------------------------
    if [[ "$dir_path" == "$HOME" ]]; then
      echo "%F{$icon_color}\uf015%f "  #
      return
    fi

    # -------------------------------------------------------------------------
    # Check cache first (performance optimization)
    # -------------------------------------------------------------------------
    local cache_key="${dir_path}"
    if [[ -n "${_LSD_DIR_ICON_CACHE[$cache_key]}" ]]; then
      echo "%F{$icon_color}${_LSD_DIR_ICON_CACHE[$cache_key]}%f "
      return
    fi

    # -------------------------------------------------------------------------
    # Method 1: Try to read from lsd icons.yaml configuration
    # -------------------------------------------------------------------------
    if [[ -f "$_LSD_ICONS_FILE" ]]; then
      icon=$(_parse_lsd_icons_yaml "$_LSD_ICONS_FILE" "$dir_name")
      if [[ -n "$icon" ]]; then
        _LSD_DIR_ICON_CACHE[$cache_key]="$icon"
        echo "%F{$icon_color}${icon}%f "
        return
      fi
    fi

    # -------------------------------------------------------------------------
    # Method 2: Get icon directly from lsd command
    # -------------------------------------------------------------------------
    icon=$(_get_lsd_icon "$dir_path")
    if [[ -n "$icon" ]]; then
      _LSD_DIR_ICON_CACHE[$cache_key]="$icon"
      echo "%F{$icon_color}${icon}%f "
      return
    fi

    # -------------------------------------------------------------------------
    # Method 3: Fallback - detect project type by contents
    # -------------------------------------------------------------------------
    if [[ -d "$dir_path/.git" ]]; then
      icon=$'\uf418'    #  Git repository
    elif [[ -f "$dir_path/package.json" ]]; then
      icon=$'\ue71e'    #  Node.js project
    elif [[ -f "$dir_path/Cargo.toml" ]]; then
      icon=$'\ue7a8'    #  Rust project
    elif [[ -f "$dir_path/go.mod" ]]; then
      icon=$'\ue724'    #  Go project
    elif [[ -f "$dir_path/requirements.txt" || -f "$dir_path/setup.py" || -f "$dir_path/pyproject.toml" ]]; then
      icon=$'\ue73c'    #  Python project
    elif [[ -f "$dir_path/Gemfile" ]]; then
      icon=$'\ue791'    #  Ruby project
    elif [[ -f "$dir_path/pom.xml" || -f "$dir_path/build.gradle" ]]; then
      icon=$'\ue738'    #  Java project
    elif [[ -f "$dir_path/composer.json" ]]; then
      icon=$'\ue73d'    #  PHP project
    elif [[ -f "$dir_path/Dockerfile" || -f "$dir_path/docker-compose.yml" || -f "$dir_path/docker-compose.yaml" ]]; then
      icon=$'\uf308'    #  Docker project
    elif [[ -f "$dir_path/Makefile" || -f "$dir_path/CMakeLists.txt" ]]; then
      icon=$'\ue779'    #  C/C++ project
    elif [[ -d "$dir_path/.terraform" || -f "$dir_path/main.tf" ]]; then
      icon=$'\uf1bb'    #  Terraform project
    elif [[ "$dir_name" == .* ]]; then
      icon=$'\uf013'    #  Hidden/config directory
    else
      icon=$'\uf07b'    #  Default folder icon
    fi

    # Cache the result
    _LSD_DIR_ICON_CACHE[$cache_key]="$icon"
    echo "%F{$icon_color}${icon}%f "
  }

  # Function to clear icon cache (useful when lsd config changes)
  function _p9k_clear_dir_icon_cache() {
    _LSD_DIR_ICON_CACHE=()
    echo "Directory icon cache cleared."
  }

  # Register the function for use in prompt expansion
  functions -M _p9k_dynamic_dir_icon 2>/dev/null

  # Configure directory classes to use our dynamic function
  # The pattern '*' matches all directories
  typeset -g POWERLEVEL9K_DIR_CLASSES=(
    '*' DYNAMIC ''
  )

  # Set the visual identifier (icon) to use our dynamic function
  typeset -g POWERLEVEL9K_DIR_DYNAMIC_VISUAL_IDENTIFIER_EXPANSION='$(_p9k_dynamic_dir_icon)'

  # ===========================================================================
  # VCS (VERSION CONTROL SYSTEM) SEGMENT
  # ===========================================================================
  # Git status display configuration

  # Icons for git status
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='\uF126 '   #  Branch icon
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'      # Untracked files indicator

  # Custom git status formatter function
  # Provides detailed, colorized git repository status
  function my_git_formatter() {
    emulate -L zsh

    # Use cached content if available
    if [[ -n $P9K_CONTENT ]]; then
      typeset -g my_git_format=$P9K_CONTENT
      return
    fi

    # Define colors based on whether terminal supports colors
    if (( $1 )); then
      # Color mode
      local       meta='%f'      # Reset to default
      local      clean='%2F'     # Green - clean state
      local   modified='%3F'     # Yellow - modified files
      local  untracked='%4F'     # Blue - untracked files
      local conflicted='%1F'     # Red - conflicts
    else
      # No color mode (loading state)
      local       meta='%f'
      local      clean='%f'
      local   modified='%f'
      local  untracked='%f'
      local conflicted='%f'
    fi

    local res

    # Branch name (truncated if > 32 chars)
    if [[ -n $VCS_STATUS_LOCAL_BRANCH ]]; then
      local branch=${(V)VCS_STATUS_LOCAL_BRANCH}
      (( $#branch > 32 )) && branch[13,-13]="…"
      res+="${clean}${(g::)POWERLEVEL9K_VCS_BRANCH_ICON}${branch//\%/%%}"
    fi

    # Tag name (shown if no branch)
    if [[ -n $VCS_STATUS_TAG && -z $VCS_STATUS_LOCAL_BRANCH ]]; then
      local tag=${(V)VCS_STATUS_TAG}
      (( $#tag > 32 )) && tag[13,-13]="…"
      res+="${meta}#${clean}${tag//\%/%%}"
    fi

    # Commit hash (shown if no branch or tag)
    [[ -z $VCS_STATUS_LOCAL_BRANCH && -z $VCS_STATUS_TAG ]] &&
      res+="${meta}@${clean}${VCS_STATUS_COMMIT[1,8]}"

    # Remote branch (if different from local)
    if [[ -n ${VCS_STATUS_REMOTE_BRANCH:#$VCS_STATUS_LOCAL_BRANCH} ]]; then
      res+="${meta}:${clean}${(V)VCS_STATUS_REMOTE_BRANCH//\%/%%}"
    fi

    # WIP indicator (if commit message contains "wip")
    if [[ $VCS_STATUS_COMMIT_SUMMARY == (|*[^[:alnum:]])(wip|WIP)(|[^[:alnum:]]*) ]]; then
      res+=" ${modified}wip"
    fi

    # Ahead/behind remote tracking branch
    if (( VCS_STATUS_COMMITS_AHEAD || VCS_STATUS_COMMITS_BEHIND )); then
      (( VCS_STATUS_COMMITS_BEHIND )) && res+=" ${clean}⇣${VCS_STATUS_COMMITS_BEHIND}"
      (( VCS_STATUS_COMMITS_AHEAD && !VCS_STATUS_COMMITS_BEHIND )) && res+=" "
      (( VCS_STATUS_COMMITS_AHEAD  )) && res+="${clean}⇡${VCS_STATUS_COMMITS_AHEAD}"
    fi

    # Ahead/behind push remote
    (( VCS_STATUS_PUSH_COMMITS_BEHIND )) && res+=" ${clean}⇠${VCS_STATUS_PUSH_COMMITS_BEHIND}"
    (( VCS_STATUS_PUSH_COMMITS_AHEAD && !VCS_STATUS_PUSH_COMMITS_BEHIND )) && res+=" "
    (( VCS_STATUS_PUSH_COMMITS_AHEAD  )) && res+="${clean}⇢${VCS_STATUS_PUSH_COMMITS_AHEAD}"

    # Stash count
    (( VCS_STATUS_STASHES        )) && res+=" ${clean}*${VCS_STATUS_STASHES}"

    # Current action (rebase, merge, etc.)
    [[ -n $VCS_STATUS_ACTION     ]] && res+=" ${conflicted}${VCS_STATUS_ACTION}"

    # File status counts
    (( VCS_STATUS_NUM_CONFLICTED )) && res+=" ${conflicted}~${VCS_STATUS_NUM_CONFLICTED}"
    (( VCS_STATUS_NUM_STAGED     )) && res+=" ${modified}+${VCS_STATUS_NUM_STAGED}"
    (( VCS_STATUS_NUM_UNSTAGED   )) && res+=" ${modified}!${VCS_STATUS_NUM_UNSTAGED}"
    (( VCS_STATUS_NUM_UNTRACKED  )) && res+=" ${untracked}${(g::)POWERLEVEL9K_VCS_UNTRACKED_ICON}${VCS_STATUS_NUM_UNTRACKED}"

    # Unknown state indicator
    (( VCS_STATUS_HAS_UNSTAGED == -1 )) && res+=" ${modified}─"

    typeset -g my_git_format=$res
  }
  functions -M my_git_formatter 2>/dev/null

  # Git status display settings
  typeset -g POWERLEVEL9K_VCS_MAX_INDEX_SIZE_DIRTY=-1          # No limit on dirty check
  typeset -g POWERLEVEL9K_VCS_DISABLED_WORKDIR_PATTERN='~'     # Disable in home (performance)
  typeset -g POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING=true

  # Use custom formatter for content
  typeset -g POWERLEVEL9K_VCS_CONTENT_EXPANSION='${$((my_git_formatter(1)))+${my_git_format}}'
  typeset -g POWERLEVEL9K_VCS_LOADING_CONTENT_EXPANSION='${$((my_git_formatter(0)))+${my_git_format}}'

  # No limits on status counts
  typeset -g POWERLEVEL9K_VCS_{STAGED,UNSTAGED,UNTRACKED,CONFLICTED,COMMITS_AHEAD,COMMITS_BEHIND}_MAX_NUM=-1

  # VCS segment colors
  typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_COLOR=2
  typeset -g POWERLEVEL9K_VCS_LOADING_VISUAL_IDENTIFIER_COLOR=
  typeset -g POWERLEVEL9K_VCS_BACKENDS=(git)                   # Only use git backend
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=2               # Green for clean
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=2           # Green with untracked
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=3            # Yellow for modified

  # ===========================================================================
  # STATUS SEGMENT (Exit Code)
  # ===========================================================================
  # Display status of last command (success/failure)

  typeset -g POWERLEVEL9K_STATUS_EXTENDED_STATES=true

  # Success indicators (disabled - using prompt_char instead)
  typeset -g POWERLEVEL9K_STATUS_OK=false
  typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=2
  typeset -g POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION='✔'

  # Pipe success
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE=true
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=2
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_VISUAL_IDENTIFIER_EXPANSION='✔'

  # Error indicators (disabled - using prompt_char instead)
  typeset -g POWERLEVEL9K_STATUS_ERROR=false
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=1
  typeset -g POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION='✘'

  # Signal errors (e.g., SIGKILL, SIGSEGV)
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=1
  typeset -g POWERLEVEL9K_STATUS_VERBOSE_SIGNAME=false
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_VISUAL_IDENTIFIER_EXPANSION='✘'

  # Pipe errors
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=1
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_VISUAL_IDENTIFIER_EXPANSION='✘'

  # ===========================================================================
  # COMMAND EXECUTION TIME SEGMENT
  # ===========================================================================
  # Show duration of commands that take longer than threshold

  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3   # Show if > 3 seconds
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0   # No decimal places
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='#6C77BB'
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'

  # ===========================================================================
  # BACKGROUND JOBS SEGMENT
  # ===========================================================================
  # Indicate when there are background jobs running

  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false        # Just show icon, no count
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=1         # Red color

  # ===========================================================================
  # USER SEGMENT
  # ===========================================================================
  # Display current username

  # Default state (local, non-root) — must be explicit or p10k hides it
  typeset -g POWERLEVEL9K_USER_DEFAULT_FOREGROUND='#583794'
  typeset -g POWERLEVEL9K_USER_DEFAULT_CONTENT_EXPANSION='%n'
  # Root state
  typeset -g POWERLEVEL9K_USER_ROOT_FOREGROUND=1
  typeset -g POWERLEVEL9K_USER_ROOT_CONTENT_EXPANSION='%B%n'

  # ===========================================================================
  # CONTEXT SEGMENT (user@hostname)
  # ===========================================================================
  # Display user and hostname (useful for SSH sessions)

  typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=1            # Red for root
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_FOREGROUND=7
  typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=7

  # Templates for different contexts
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE='󰈸'           # Lightning bolt for root
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_TEMPLATE='%n@%m'
  typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%n@%m'

  # Hide context in default/sudo local sessions
  typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_{CONTENT,VISUAL_IDENTIFIER}_EXPANSION=

  # ===========================================================================
  # TIME SEGMENT
  # ===========================================================================
  # Display current time (if added to prompt elements)

  typeset -g POWERLEVEL9K_TIME_FOREGROUND=6                    # Cyan color
  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'           # 24-hour format
  typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false         # Update on every prompt

  # ===========================================================================
  # ADVANCED SETTINGS
  # ===========================================================================

  # Transient prompt - minimize previous prompts (disabled)
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off

  # Instant prompt - show prompt immediately before full initialization
  # Options: off, quiet, verbose
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose

  # Disable hot reload of configuration (better performance)
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

  # Reload configuration if p10k is already loaded
  (( ! $+functions[p10k] )) || p10k reload
}

# =============================================================================
# CONFIGURATION FILE PATH
# =============================================================================
# Tell p10k configure which file to overwrite
typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}

# Restore original shell options
(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
